import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  fr: {
    'nav.home': 'Accueil',
    'nav.testimonials': 'Témoignages',
    'nav.courses': 'Cours',
    'nav.qcm': 'QCM',
    'nav.admin': 'Admin',
    'nav.logout': 'Déconnexion',
    'nav.login': 'Connexion',
    'footer.desc': 'Formation IFR professionnelle pour pilotes PPL et CPL. Maîtrisez le pilotage sans visibilité avec une pédagogie adaptée.',
    'footer.modules': 'Modules',
    'footer.contact': 'Contact',
    'footer.rights': '© 2026 Aviation Online. Tous droits réservés.',
    'footer.legal': 'Mentions Légales',
    'footer.terms': 'CGU',
    'home.hero.title1': 'Maîtrisez le',
    'home.hero.title2': 'Vol et les Procédures IFR',
    'home.hero.desc': 'La plateforme de référence pour les pilotes envisageant ou en cours de formation pratique IR, ainsi que pour les pilotes qualifiés souhaitant maintenir leur niveau pour une prorogation ou une sélection compagnie.',
    'home.hero.start': 'Commencer la formation',
    'home.hero.price': 'Accès complet à 79€',
    'home.features.1.title': 'Expertise Instructeur',
    'home.features.1.desc': 'Formation conçue par un instructeur expert avec plus de 30 ans d\'expérience en ATO.',
    'home.features.2.title': 'Pédagogie IFR',
    'home.features.2.desc': 'Une approche structurée pour maîtriser le pilotage sans visibilité et réussir vos sélections en compagnie aérienne.',
    'home.features.3.title': 'Succès Étudiants',
    'home.features.3.desc': 'Des centaines de pilotes formés qui volent aujourd\'hui en compagnie grâce à mes méthodes éprouvées.',
    'home.stats.slides': 'Slides de cours',
    'home.stats.video': 'Vidéos pédagogiques',
    'home.stats.qcm': 'Questions de QCM',
    'home.pricing.special': 'Offre Spéciale',
    'home.pricing.title': 'Accès Illimité à Vie',
    'home.pricing.desc': 'Profitez de l\'intégralité des modules, des schémas pédagogiques et du support instructeur pour un tarif unique et définitif.',
    'home.pricing.payment': 'Paiement unique',
    'home.pricing.signup': 'S\'inscrire maintenant',
    'home.audience.title': 'Une formation adaptée à votre parcours',
    'home.audience.desc': 'Que vous soyez en début de formation ou pilote expérimenté, nos modules répondent à vos besoins spécifiques.',
    'home.audience.1.title': 'Envisageant une qualification IR',
    'home.audience.1.desc': 'Préparez le terrain avant même de monter dans l\'avion. Familiarisez-vous avec les concepts fondamentaux, le circuit visuel et la philosophie du vol aux instruments pour aborder votre formation pratique avec une longueur d\'avance.',
    'home.audience.2.title': 'En cours de formation pratique IR',
    'home.audience.2.desc': 'Complétez vos séances en vol par une base théorique solide et des procédures claires. Gagnez en sérénité et en efficacité lors de vos passages au simulateur ou en avion en maîtrisant parfaitement les trajectoires.',
    'home.audience.3.title': 'Maintien de compétences & Sélections',
    'home.audience.3.desc': 'Pilotes déjà qualifiés : révisez vos classiques pour une prorogation ou préparez-vous aux exigences des sélections en compagnie aérienne. Maintenez un niveau d\'excellence technique et opérationnel constant.',
    'home.instructor.badge': 'Votre Instructeur',
    'home.instructor.desc1': 'Instructeur sur simulateur de vol depuis 1985, expert en pédagogie aéronautique avec plus de 25 000 heures d\'instruction.',
    'home.instructor.bullet1': 'Formations IFR/IR de pilotes de ligne et de pilotes privés.',
    'home.instructor.bullet2': 'Formateur d’instructeurs IR (IRI).',
    'home.instructor.bullet3': 'Formations MCC (travail en équipage) MCCI.',
    'home.instructor.bullet4': 'Formateur d’instructeurs MCC (I-MCCI).',
    'home.instructor.path': 'Parcours & Qualifications',
    'home.instructor.path1': 'Armée de l’Air',
    'home.instructor.path2': 'Aéroformation',
    'home.instructor.path3': 'Aéronautique Formation',
    'home.instructor.path4': 'Airways Formation',
    'home.instructor.path5': 'Airways College',
    'home.instructor.path6': 'Aéro-Pyrénées',
    'home.modules.title': 'Programme de Formation',
    'home.modules.desc': 'Un cursus complet et structuré pour maîtriser chaque aspect du vol aux instruments.',
    'home.testimonials.title': 'Ils ont réussi avec nous',
    'home.testimonials.desc': 'Découvrez les retours de nos élèves qui volent aujourd\'hui en compagnie.',
    'home.cta.title': 'Prêt à franchir le pas vers l\'IFR ?',
    'home.cta.price': '79€',
    'home.cta.price_desc': '/ accès à vie',
    'home.cta.bullet1': 'Tous les modules théoriques',
    'home.cta.bullet2': 'Mises à jour gratuites',
    'home.cta.bullet3': 'Support instructeur',
    'home.cta.btn': 'S\'inscrire maintenant',
    'home.testimonials.all.title': 'Consulter tous les avis',
    'home.testimonials.all.desc': 'Retrouvez l\'intégralité des témoignages de mes élèves pilotes sur notre page dédiée.',
    'home.testimonials.all.btn': 'Voir les témoignages',
    'testimonials.back': 'Retour à l\'accueil',
    'testimonials.title': 'Témoignages',
    'testimonials.subtitle': 'Formation Pilotes',
    'testimonials.desc': 'Découvrez les retours d\'expérience de mes stagiaires. Des centaines de pilotes ont déjà fait confiance à Aviation Online pour leur formation IFR et leur préparation aux sélections.',
    'testimonials.cta.title': 'Rejoignez la communauté des',
    'testimonials.cta.title_highlight': 'pilotes d\'élite',
    'testimonials.cta.desc': 'Notre formation est conçue pour vous amener au niveau d\'exigence des plus grandes compagnies aériennes. Ne laissez rien au hasard pour votre carrière.',
    'testimonials.cta.bullet1': 'Accès immédiat à tous les modules',
    'testimonials.cta.bullet2': 'Support instructeur personnalisé',
    'testimonials.cta.bullet3': 'Mises à jour régulières EASA',
    'testimonials.cta.bullet4': 'Assistant IA spécialisé',
    'testimonials.cta.stat1.value': '500+',
    'testimonials.cta.stat1.label': 'Pilotes formés',
    'testimonials.cta.stat2.value': '98%',
    'testimonials.cta.stat2.label': 'Taux de réussite',
    'testimonials.cta.btn': 'Commencer ma formation aujourd\'hui',
    'qcm.title': 'Plateforme QCM - Testez vos connaissances théoriques IFR',
    'qcm.available': 'Quiz disponibles',
    'qcm.history': 'Historique',
    'qcm.start': 'Démarrer le test',
    'qcm.empty': 'Aucun quiz disponible pour le moment.',
    'qcm.history.empty': "Vous n'avez pas encore passé de quiz.",
    'qcm.history.date': 'Date',
    'qcm.history.quiz': 'Quiz',
    'qcm.history.score': 'Score',
    'qcm.history.result': 'Résultat',
    'qcm.results.title': 'Test Terminé !',
    'qcm.results.success': 'de réussite',
    'qcm.results.correct': 'Correct',
    'qcm.results.errors': 'Erreurs',
    'qcm.results.restart': 'Recommencer',
    'qcm.results.back': 'Retour aux quiz',
    'qcm.question.quit': 'Quitter le test',
    'qcm.question.of': 'sur',
    'qcm.question.validate': 'Valider la réponse',
    'qcm.question.next': 'Question suivante',
    'qcm.question.see_results': 'Voir les résultats',
    'dashboard.loading': 'Chargement de vos cours...',
    'dashboard.title': 'Votre Formation IR',
    'dashboard.subtitle.paid': 'Vous avez accès à tout le contenu.',
    'dashboard.subtitle.free': 'Abonnez-vous pour débloquer tous les modules.',
    'dashboard.payment.check': 'Vérifier mon paiement',
    'dashboard.payment.checking': 'Vérification...',
    'dashboard.payment.force': 'Forcer l\'activation (Admin)',
    'dashboard.payment.success.title': 'Paiement réussi !',
    'dashboard.payment.success.desc': 'Votre accès complet a été activé. Bienvenue à bord !',
    'dashboard.payment.pending.title': 'Vérification de votre paiement...',
    'dashboard.payment.pending.desc': 'Nous confirmons votre transaction auprès de Stripe. Cela peut prendre quelques secondes.',
    'dashboard.module.locked': 'Module verrouillé',
    'dashboard.module.unlock': 'Débloquer l\'accès complet',
    'dashboard.course.read': 'Lire le cours',
    'dashboard.course.pdf': 'Télécharger le PDF',
    'course.loading': 'Chargement du cours...',
    'course.not_found': 'Cours non trouvé.',
    'course.back': 'Retour au tableau de bord',
    'course.support': 'Support de cours',
    'course.security': 'Consultation en ligne uniquement pour des raisons de sécurité.',
    'course.prev': 'Précédent',
    'course.next': 'Suivant',
    'course.finished': 'Module terminé',
    'course.back_dashboard': 'Retour au dashboard',
    'login.welcome_back': 'Bon retour parmi nous',
    'login.create_account': 'Créer votre compte',
    'login.forgot_password': 'Mot de passe oublié',
    'login.desc_login': 'Accédez à votre formation IFR professionnelle.',
    'login.desc_register': 'Rejoignez Aviation Online et maîtrisez le vol IFR.',
    'login.desc_forgot': 'Entrez votre email pour réinitialiser votre mot de passe.',
    'login.error.invalid_credentials': 'Email ou mot de passe incorrect.',
    'login.error.email_in_use': 'Cet email est déjà utilisé.',
    'login.error.register': 'Erreur lors de l\'inscription: ',
    'login.error.reset_failed': 'Impossible d\'envoyer l\'email de réinitialisation.',
    'login.success.reset_sent': 'Un email de réinitialisation a été envoyé.',
    'login.firstname': 'Prénom',
    'login.lastname': 'Nom',
    'login.email': 'Email',
    'login.password': 'Mot de passe',
    'login.forgot_question': 'Oublié ?',
    'login.phone': 'Téléphone (facultatif)',
    'login.address': 'Adresse postale',
    'login.zipcode': 'Code Postal',
    'login.city': 'Ville',
    'login.country': 'Pays',
    'login.btn.login': 'Se connecter',
    'login.btn.register': 'S\'inscrire',
    'login.btn.reset': 'Réinitialiser',
    'login.loading': 'Chargement...',
    'login.or_continue_with': 'Ou continuer avec',
    'login.no_account': 'Pas encore de compte ?',
    'login.back_to_login': 'Retour à la connexion',
    'payment.login_required': 'Veuillez vous connecter pour procéder au paiement.',
    'payment.server_error': 'Erreur serveur',
    'payment.popup_blocked': 'La page de paiement Stripe s\'ouvre dans un nouvel onglet. Si rien ne se passe, veuillez autoriser les popups ou ouvrir l\'application dans un nouvel onglet.',
    'payment.missing_url': 'URL de session Stripe manquante.',
    'payment.error': 'Erreur de paiement :',
    'payment.already_paid': 'Vous avez déjà accès !',
    'payment.already_paid_desc': 'Votre abonnement est actif. Profitez de votre formation.',
    'payment.go_dashboard': 'Aller au tableau de bord',
    'payment.cancelled': 'Le paiement a été annulé. Vous pouvez réessayer quand vous le souhaitez.',
    'payment.iframe_warning': 'Note : Vous êtes dans un aperçu. Pour un paiement sécurisé, veuillez ouvrir l\'application dans un nouvel onglet.',
    'payment.title': 'Débloquez votre Formation IR',
    'payment.subtitle': 'Un investissement pour votre carrière de pilote.',
    'payment.feature1.title': 'Accès Illimité',
    'payment.feature1.desc': 'Tous les modules actuels et futurs inclus sans frais supplémentaires.',
    'payment.feature2.title': 'Pédagogie d\'Expert',
    'payment.feature2.desc': 'Des cours structurés par des instructeurs IFR pour une réussite garantie.',
    'payment.feature3.title': 'Paiement Sécurisé',
    'payment.feature3.desc': 'Transaction sécurisée via Stripe. Vos données sont protégées.',
    'payment.offer': 'Offre Lancement',
    'payment.product': 'Formation Complète IR',
    'payment.benefit1': 'Accès à vie',
    'payment.benefit2': 'Support par email',
    'payment.benefit3': 'Certificat de complétion',
    'payment.btn.pay': 'Payer maintenant',
    'payment.btn.loading': 'Initialisation...',
    'payment.terms': 'En cliquant, vous acceptez nos conditions générales de vente.',
    'terms.title': 'Conditions Générales d\'Utilisation (CGU)',
    'terms.section1.title': '1. Objet',
    'terms.section1.content': 'Les présentes Conditions Générales d\'Utilisation (CGU) ont pour objet de définir les modalités de mise à disposition des services du site Aviation Online. Toute utilisation du site implique l\'acceptation pleine et entière des présentes conditions par l\'utilisateur.',
    'terms.section2.title': '2. Accès aux services et Tarifs',
    'terms.section2.content': 'L\'accès aux modules de formation est réservé aux utilisateurs ayant souscrit à l\'offre payante. Le tarif en vigueur est de <strong>79€ TTC</strong> pour un accès à vie (sauf modification ultérieure des conditions). Le paiement s\'effectue par carte bancaire via la plateforme sécurisée <strong>Stripe</strong>.',
    'terms.section3.title': '3. Droit de rétractation et Remboursement',
    'terms.section3.content1': 'Conformément à l\'article L221-28 du Code de la consommation, le droit de rétractation ne peut être exercé pour les contrats de fourniture d\'un contenu numérique non fourni sur un support matériel dont l\'exécution a commencé après accord préalable exprès du consommateur et renoncement exprès à son droit de rétractation.',
    'terms.section3.content2': 'En accédant immédiatement aux modules de formation après paiement, l\'utilisateur accepte de renoncer à son droit de rétractation de 14 jours.',
    'terms.section4.title': '4. Propriété intellectuelle',
    'terms.section4.content': 'Les contenus de formation (vidéos, textes, schémas, QCM) sont protégés par le droit d\'auteur. Ils sont destinés à un usage strictement personnel et non transférable. Toute reproduction, diffusion, partage de compte ou utilisation à des fins commerciales est strictement interdite et pourra faire l\'objet de poursuites.',
    'terms.section5.title': '5. Responsabilité',
    'terms.section5.content': 'Aviation Online s\'efforce de fournir des informations pédagogiques de haute qualité. Toutefois, ces formations sont à but informatif et ne remplacent en aucun cas une formation officielle dispensée par un organisme agréé (ATO/DTO). L\'éditeur ne saurait être tenu responsable des résultats aux examens officiels ou de l\'utilisation faite de ces connaissances en vol réel.',
    'terms.section6.title': '6. Règlement des litiges',
    'terms.section6.content': 'Les présentes CGU sont soumises à la loi française. En cas de litige, et après tentative de résolution amiable, compétence est attribuée aux tribunaux français compétents.',
    'legal.title': 'Mentions Légales',
    'legal.section1.title': '1. Éditeur du site',
    'legal.section1.p1': 'Le site <strong>Aviation Online</strong> est édité par :',
    'legal.section1.p2': 'Entrepreneur Individuel (EI)',
    'legal.section1.p3': 'Siège social : 1bis, Avenue Justin Maurice 47520 LE PASSAGE',
    'legal.section1.p4': 'TVA Intracommunautaire : Non applicable, art. 293 B du CGI',
    'legal.section1.p5': 'Téléphone : 06 63 09 10 36',
    'legal.section2.title': '2. Directeur de la publication',
    'legal.section2.p1': 'Monsieur Jean-Claude CHENARD',
    'legal.section3.title': '3. Hébergement',
    'legal.section3.p1': 'Le site est hébergé par :',
    'legal.section4.title': '4. Propriété intellectuelle',
    'legal.section4.p1': 'L\'ensemble des éléments constituant le site Aviation Online (textes, graphismes, logiciels, photographies, images, vidéos, sons, plans, noms, logos, marques, créations et œuvres protégeables diverses, bases de données, etc.) ainsi que le site lui-même, relèvent des législations françaises et internationales sur le droit d\'auteur et la propriété intellectuelle.',
    'legal.section4.p2': 'Ces éléments sont la propriété exclusive de Jean-Claude CHENARD. Toute reproduction, représentation, modification, publication, adaptation de tout ou partie des éléments du site, quel que soit le moyen ou le procédé utilisé, est interdite, sauf autorisation écrite préalable.',
    'legal.section5.title': '5. Données personnelles (RGPD)',
    'legal.section5.p1': 'Conformément au Règlement Général sur la Protection des Données (RGPD), vous disposez d\'un droit d\'accès, de rectification, de suppression et d\'opposition aux données personnelles vous concernant. Pour exercer ce droit, vous pouvez nous contacter par email à : <strong>contact@aviationonline.net</strong>.',
    'app.error.title': 'Erreur de connexion',
    'app.error.retry': 'Réessayer',
    'app.loading': 'Chargement de votre session...',
    'app.errorBoundary.title': 'Oups ! Quelque chose s\'est mal passé.',
    'app.errorBoundary.defaultMsg': 'Une erreur inattendue est survenue.',
    'app.errorBoundary.reload': 'Recharger la page',
    'auth.error.deleted': 'Votre compte a été supprimé ou n\'existe plus.',
    'auth.error.sync': 'Erreur lors de la synchronisation du profil.',
    'auth.error.read': 'Impossible de lire votre profil. Vérifiez vos permissions.',
    'auth.error.auth': 'Erreur d\'authentification.',
    'auth.error.google': 'Échec de la connexion Google.',
    'qcm.alert.noQuestions': 'Ce quiz ne contient pas encore de questions.',
    'dashboard.confirm.forceActivate': 'Voulez-vous forcer l\'activation de cet utilisateur ?',
    'dashboard.alert.debugCopied': 'Infos de debug copiées !',
    'dashboard.error.forceActivate': 'Erreur lors de l\'activation forcée.',
    'dashboard.status.paid': 'Vous avez accès à tout le contenu.',
    'dashboard.status.unpaid': 'Abonnez-vous pour débloquer tous les modules.',
    'dashboard.btn.checking': 'Vérification...',
    'dashboard.btn.alreadyPaid': 'Déjà payé ? Cliquez ici pour activer votre accès'
  },
  en: {
    'nav.home': 'Home',
    'nav.testimonials': 'Testimonials',
    'nav.courses': 'Courses',
    'nav.qcm': 'Quizzes',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',
    'nav.login': 'Login',
    'footer.desc': 'Professional IFR training for PPL and CPL pilots. Master instrument flying with adapted pedagogy.',
    'footer.modules': 'Modules',
    'footer.contact': 'Contact',
    'footer.rights': '© 2026 Aviation Online. All rights reserved.',
    'footer.legal': 'Legal Mentions',
    'footer.terms': 'Terms of Service',
    'home.hero.title1': 'Master',
    'home.hero.title2': 'IFR Flight and Procedures',
    'home.hero.desc': 'The reference platform for pilots considering or undergoing practical IR training, as well as for qualified pilots wishing to maintain their level for renewal or airline selection.',
    'home.hero.start': 'Start Training',
    'home.hero.price': 'Full access for 79€',
    'home.features.1.title': 'Instructor Expertise',
    'home.features.1.desc': 'Training designed by an expert instructor with over 30 years of ATO experience.',
    'home.features.2.title': 'IFR Pedagogy',
    'home.features.2.desc': 'A structured approach to mastering instrument flying and succeeding in your airline selections.',
    'home.features.3.title': 'Student Success',
    'home.features.3.desc': 'Hundreds of trained pilots flying today in airlines thanks to my proven methods.',
    'home.stats.slides': 'Course Slides',
    'home.stats.video': 'Educational Videos',
    'home.stats.qcm': 'Quiz Questions',
    'home.pricing.special': 'Special Offer',
    'home.pricing.title': 'Unlimited Lifetime Access',
    'home.pricing.desc': 'Enjoy all modules, educational diagrams, and instructor support for a single, definitive price.',
    'home.pricing.payment': 'One-time payment',
    'home.pricing.signup': 'Sign up now',
    'home.audience.title': 'Training adapted to your journey',
    'home.audience.desc': 'Whether you are just starting your training or are an experienced pilot, our modules meet your specific needs.',
    'home.audience.1.title': 'Considering an IR qualification',
    'home.audience.1.desc': 'Prepare the ground before even getting into the plane. Familiarize yourself with fundamental concepts, visual scanning, and the philosophy of instrument flying to approach your practical training with a head start.',
    'home.audience.2.title': 'Currently in practical IR training',
    'home.audience.2.desc': 'Complement your flight sessions with a solid theoretical foundation and clear procedures. Gain peace of mind and efficiency during your simulator or flight sessions by perfectly mastering the trajectories.',
    'home.audience.3.title': 'Skills Maintenance & Selections',
    'home.audience.3.desc': 'Already qualified pilots: review your basics for a renewal or prepare for the requirements of airline selections. Maintain a constant level of technical and operational excellence.',
    'home.instructor.badge': 'Your Instructor',
    'home.instructor.desc1': 'Flight simulator instructor since 1985, expert in aeronautical pedagogy with over 25,000 hours of instruction.',
    'home.instructor.bullet1': 'IFR/IR training for airline and private pilots.',
    'home.instructor.bullet2': 'IR Instructor Trainer (IRI).',
    'home.instructor.bullet3': 'MCC (Multi-Crew Cooperation) Training MCCI.',
    'home.instructor.bullet4': 'MCC Instructor Trainer (I-MCCI).',
    'home.instructor.path': 'Career & Qualifications',
    'home.instructor.path1': 'French Air Force',
    'home.instructor.path2': 'Aéroformation',
    'home.instructor.path3': 'Aéronautique Formation',
    'home.instructor.path4': 'Airways Formation',
    'home.instructor.path5': 'Airways College',
    'home.instructor.path6': 'Aéro-Pyrénées',
    'home.modules.title': 'Training Program',
    'home.modules.desc': 'A complete and structured curriculum to master every aspect of instrument flying.',
    'home.testimonials.title': 'They succeeded with us',
    'home.testimonials.desc': 'Discover the feedback from our students who are flying in airlines today.',
    'home.cta.title': 'Ready to take the step towards IFR?',
    'home.cta.price': '79€',
    'home.cta.price_desc': '/ lifetime access',
    'home.cta.bullet1': 'All theoretical modules',
    'home.cta.bullet2': 'Free updates',
    'home.cta.bullet3': 'Instructor support',
    'home.cta.btn': 'Sign up now',
    'home.testimonials.all.title': 'View all reviews',
    'home.testimonials.all.desc': 'Find all the testimonials from my student pilots on our dedicated page.',
    'home.testimonials.all.btn': 'See testimonials',
    'testimonials.back': 'Back to home',
    'testimonials.title': 'Testimonials',
    'testimonials.subtitle': 'Pilot Training',
    'testimonials.desc': 'Discover the feedback from my trainees. Hundreds of pilots have already trusted Aviation Online for their IFR training and selection preparation.',
    'testimonials.cta.title': 'Join the community of',
    'testimonials.cta.title_highlight': 'elite pilots',
    'testimonials.cta.desc': 'Our training is designed to bring you to the demanding level of major airlines. Leave nothing to chance for your career.',
    'testimonials.cta.bullet1': 'Immediate access to all modules',
    'testimonials.cta.bullet2': 'Personalized instructor support',
    'testimonials.cta.bullet3': 'Regular EASA updates',
    'testimonials.cta.bullet4': 'Specialized AI assistant',
    'testimonials.cta.stat1.value': '500+',
    'testimonials.cta.stat1.label': 'Pilots trained',
    'testimonials.cta.stat2.value': '98%',
    'testimonials.cta.stat2.label': 'Success rate',
    'testimonials.cta.btn': 'Start my training today',
    'qcm.title': 'Quiz Platform - Test your theoretical IFR knowledge',
    'qcm.available': 'Available Quizzes',
    'qcm.history': 'History',
    'qcm.start': 'Start Test',
    'qcm.empty': 'No quizzes available at the moment.',
    'qcm.history.empty': "You haven't taken any quizzes yet.",
    'qcm.history.date': 'Date',
    'qcm.history.quiz': 'Quiz',
    'qcm.history.score': 'Score',
    'qcm.history.result': 'Result',
    'qcm.results.title': 'Test Completed!',
    'qcm.results.success': 'success rate',
    'qcm.results.correct': 'Correct',
    'qcm.results.errors': 'Errors',
    'qcm.results.restart': 'Restart',
    'qcm.results.back': 'Back to quizzes',
    'qcm.question.quit': 'Quit test',
    'qcm.question.of': 'of',
    'qcm.question.validate': 'Submit answer',
    'qcm.question.next': 'Next question',
    'qcm.question.see_results': 'See results',
    'dashboard.loading': 'Loading your courses...',
    'dashboard.title': 'Your IR Training',
    'dashboard.subtitle.paid': 'You have access to all content.',
    'dashboard.subtitle.free': 'Subscribe to unlock all modules.',
    'dashboard.payment.check': 'Check my payment',
    'dashboard.payment.checking': 'Checking...',
    'dashboard.payment.force': 'Force activation (Admin)',
    'dashboard.payment.success.title': 'Payment successful!',
    'dashboard.payment.success.desc': 'Your full access has been activated. Welcome aboard!',
    'dashboard.payment.pending.title': 'Verifying your payment...',
    'dashboard.payment.pending.desc': 'We are confirming your transaction with Stripe. This may take a few seconds.',
    'dashboard.module.locked': 'Locked module',
    'dashboard.module.unlock': 'Unlock full access',
    'dashboard.course.read': 'Read course',
    'dashboard.course.pdf': 'Download PDF',
    'course.loading': 'Loading course...',
    'course.not_found': 'Course not found.',
    'course.back': 'Back to dashboard',
    'course.support': 'Course material',
    'course.security': 'Online viewing only for security reasons.',
    'course.prev': 'Previous',
    'course.next': 'Next',
    'course.finished': 'Module completed',
    'course.back_dashboard': 'Back to dashboard',
    'login.welcome_back': 'Welcome back',
    'login.create_account': 'Create your account',
    'login.forgot_password': 'Forgot password',
    'login.desc_login': 'Access your professional IFR training.',
    'login.desc_register': 'Join Aviation Online and master IFR flying.',
    'login.desc_forgot': 'Enter your email to reset your password.',
    'login.error.invalid_credentials': 'Invalid email or password.',
    'login.error.email_in_use': 'This email is already in use.',
    'login.error.register': 'Registration error: ',
    'login.error.reset_failed': 'Unable to send reset email.',
    'login.success.reset_sent': 'A reset email has been sent.',
    'login.firstname': 'First name',
    'login.lastname': 'Last name',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.forgot_question': 'Forgot?',
    'login.phone': 'Phone (optional)',
    'login.address': 'Postal address',
    'login.zipcode': 'Zip code',
    'login.city': 'City',
    'login.country': 'Country',
    'login.btn.login': 'Log in',
    'login.btn.register': 'Sign up',
    'login.btn.reset': 'Reset',
    'login.loading': 'Loading...',
    'login.or_continue_with': 'Or continue with',
    'login.no_account': 'Don\'t have an account yet?',
    'login.back_to_login': 'Back to login',
    'payment.login_required': 'Please log in to proceed with payment.',
    'payment.server_error': 'Server error',
    'payment.popup_blocked': 'The Stripe payment page opens in a new tab. If nothing happens, please allow popups or open the app in a new tab.',
    'payment.missing_url': 'Missing Stripe session URL.',
    'payment.error': 'Payment error:',
    'payment.already_paid': 'You already have access!',
    'payment.already_paid_desc': 'Your subscription is active. Enjoy your training.',
    'payment.go_dashboard': 'Go to dashboard',
    'payment.cancelled': 'Payment was cancelled. You can try again whenever you want.',
    'payment.iframe_warning': 'Note: You are in a preview. For secure payment, please open the app in a new tab.',
    'payment.title': 'Unlock your IR Training',
    'payment.subtitle': 'An investment in your pilot career.',
    'payment.feature1.title': 'Unlimited Access',
    'payment.feature1.desc': 'All current and future modules included at no extra cost.',
    'payment.feature2.title': 'Expert Pedagogy',
    'payment.feature2.desc': 'Courses structured by IFR instructors for guaranteed success.',
    'payment.feature3.title': 'Secure Payment',
    'payment.feature3.desc': 'Secure transaction via Stripe. Your data is protected.',
    'payment.offer': 'Launch Offer',
    'payment.product': 'Complete IR Training',
    'payment.benefit1': 'Lifetime access',
    'payment.benefit2': 'Email support',
    'payment.benefit3': 'Certificate of completion',
    'payment.btn.pay': 'Pay now',
    'payment.btn.loading': 'Initializing...',
    'payment.terms': 'By clicking, you accept our terms and conditions.',
    'terms.title': 'Terms of Service (ToS)',
    'terms.section1.title': '1. Purpose',
    'terms.section1.content': 'These Terms of Service (ToS) aim to define the terms of provision of the services of the Aviation Online website. Any use of the site implies full and complete acceptance of these conditions by the user.',
    'terms.section2.title': '2. Access to services and Pricing',
    'terms.section2.content': 'Access to the training modules is reserved for users who have subscribed to the paid offer. The current price is <strong>79€ incl. VAT</strong> for lifetime access (unless the conditions are subsequently modified). Payment is made by credit card via the secure <strong>Stripe</strong> platform.',
    'terms.section3.title': '3. Right of withdrawal and Refund',
    'terms.section3.content1': 'In accordance with Article L221-28 of the Consumer Code, the right of withdrawal cannot be exercised for contracts for the supply of digital content not supplied on a tangible medium whose execution has begun after prior express agreement of the consumer and express waiver of his right of withdrawal.',
    'terms.section3.content2': 'By immediately accessing the training modules after payment, the user agrees to waive their 14-day right of withdrawal.',
    'terms.section4.title': '4. Intellectual property',
    'terms.section4.content': 'The training content (videos, texts, diagrams, MCQs) is protected by copyright. They are intended for strictly personal and non-transferable use. Any reproduction, distribution, account sharing or use for commercial purposes is strictly prohibited and may be subject to prosecution.',
    'terms.section5.title': '5. Responsibility',
    'terms.section5.content': 'Aviation Online strives to provide high quality educational information. However, these trainings are for informational purposes and do not in any way replace official training provided by an approved organization (ATO/DTO). The publisher cannot be held responsible for the results of official exams or the use made of this knowledge in real flight.',
    'terms.section6.title': '6. Dispute resolution',
    'terms.section6.content': 'These ToS are subject to French law. In the event of a dispute, and after an attempt at an amicable resolution, jurisdiction is assigned to the competent French courts.',
    'legal.title': 'Legal Mentions',
    'legal.section1.title': '1. Site publisher',
    'legal.section1.p1': 'The <strong>Aviation Online</strong> website is published by:',
    'legal.section1.p2': 'Individual Entrepreneur (EI)',
    'legal.section1.p3': 'Head office: 1bis, Avenue Justin Maurice 47520 LE PASSAGE',
    'legal.section1.p4': 'Intracommunity VAT: Not applicable, art. 293 B of the CGI',
    'legal.section1.p5': 'Phone: +33 6 63 09 10 36',
    'legal.section2.title': '2. Publication Director',
    'legal.section2.p1': 'Mr. Jean-Claude CHENARD',
    'legal.section3.title': '3. Hosting',
    'legal.section3.p1': 'The site is hosted by:',
    'legal.section4.title': '4. Intellectual property',
    'legal.section4.p1': 'All elements constituting the Aviation Online website (texts, graphics, software, photographs, images, videos, sounds, plans, names, logos, brands, various protectable creations and works, databases, etc.) as well as the site itself, are subject to French and international legislation on copyright and intellectual property.',
    'legal.section4.p2': 'These elements are the exclusive property of Jean-Claude CHENARD. Any reproduction, representation, modification, publication, adaptation of all or part of the elements of the site, whatever the means or process used, is prohibited, except with prior written authorization.',
    'legal.section5.title': '5. Personal data (GDPR)',
    'legal.section5.p1': 'In accordance with the General Data Protection Regulation (GDPR), you have the right to access, rectify, delete and oppose personal data concerning you. To exercise this right, you can contact us by email at: <strong>contact@aviationonline.net</strong>.',
    'app.error.title': 'Connection error',
    'app.error.retry': 'Retry',
    'app.loading': 'Loading your session...',
    'app.errorBoundary.title': 'Oops! Something went wrong.',
    'app.errorBoundary.defaultMsg': 'An unexpected error occurred.',
    'app.errorBoundary.reload': 'Reload page',
    'auth.error.deleted': 'Your account has been deleted or no longer exists.',
    'auth.error.sync': 'Error synchronizing profile.',
    'auth.error.read': 'Unable to read your profile. Check your permissions.',
    'auth.error.auth': 'Authentication error.',
    'auth.error.google': 'Google login failed.',
    'qcm.alert.noQuestions': 'This quiz does not contain any questions yet.',
    'dashboard.confirm.forceActivate': 'Do you want to force the activation of this user?',
    'dashboard.alert.debugCopied': 'Debug info copied!',
    'dashboard.error.forceActivate': 'Error during forced activation.',
    'dashboard.status.paid': 'You have access to all content.',
    'dashboard.status.unpaid': 'Subscribe to unlock all modules.',
    'dashboard.btn.checking': 'Checking...',
    'dashboard.btn.alreadyPaid': 'Already paid? Click here to activate your access'
  }
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('fr');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'fr' || savedLang === 'en')) {
      setLanguageState(savedLang);
      document.documentElement.lang = savedLang;
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
